import './globals.css'; // Include if you have global styles

export const metadata = {
  title: 'bannnja-shop',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}